name: Build Portable EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build EXE inside Docker
        run: |
          docker build -t builder-img .
          # ایجاد یک کانتینر موقت برای استخراج فایل
          docker create --name temp-container builder-img
          docker cp temp-container:/app/dist/saino-forge.exe ./saino-forge.exe
          docker rm temp-container

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SainoForge-Windows
          path: ./saino-forge.exe
